swagger: "2.0"

info:

  title: Text Analysis API
  
  version: 1.0.0

paths:

  /analyze:
  
    post:
    
      responses:
      
        200:
        
          description: Success
          
          schema:
          
            $ref: '#/definitions/Response'
            
definitions:

  Response:
  
    type: object
    
    properties:
    
      response:
      
        $ref: '#/definitions/ResponseData'
        
  ResponseData:
  
    type: object
    
    properties:
    
      prompt:
      
        type: string
        
      prompt_id:
      
        type: string
        
      model_version:
      
        type: integer
        
      timestamp:
      
        type: string
        format: date-time
        
      response_id:
      
        type: string
        
      completion:
      
        $ref: '#/definitions/Completion'
        
  Completion:
  
    type: object
    
    properties:
    
      appeal:
      
        type: array
        
        items:
        
          $ref: '#/definitions/Category'
          
      credibility:
      
        type: array
        
        items:
        
          $ref: '#/definitions/Category'
          
      consideration:
      
        type: array
        
        items:
        
          $ref: '#/definitions/Category'
          
      integration:
      
        type: array
        
        items:
        
          $ref: '#/definitions/Category'
          
      clarification:
      
        type: array
        
        items:
        
          $ref: '#/definitions/Category'

  Category:
  
    type: object
    
    properties:
    
      annotated_text:
      
        type: string
        
        items:
        
          type: string
          
      classification:
      
        type: string
        
      suggestions:
      
        type: array
        
        items:
        
          type: string
          
      explanation:
      
        type: array
        
        items:
        
          type: string
          
      metrics:
      
        type: object