swagger: "2.0"

info:
  title: Sample API
  version: 1.0.0

paths:
  /example:
    post:
      summary: Example endpoint
      parameters:
        - in: body
          name: requestBody
          description: Request body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              age:
                type: integer
                minimum: 0
                maximum: 120
            required:
              - name
              - age
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error